"""requirements-lock.txt must track uv.lock exactly.

action.yml installs from requirements-lock.txt, not uv.lock, so the GitHub
Action gets the exact provider SDK versions this repo's own test suite runs
against (see Makefile's `lock-action` target). A `uv add`/`uv lock` that
updates uv.lock without also regenerating requirements-lock.txt would leave
the Action free to drift onto an untested release again -- this is the same
class of gap that once let it install a langchain-anthropic release which
renamed a routine Anthropic connection error into a class the report had
never seen before.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _requirements_lock_versions() -> dict[str, str]:
    versions = {}
    for line in (ROOT / "requirements-lock.txt").read_text().splitlines():
        match = re.match(r"^([A-Za-z0-9_.-]+)==([^\s;]+)", line)
        if match:
            versions[match.group(1).lower()] = match.group(2)
    return versions


def test_requirements_lock_matches_a_fresh_export():
    """Regenerate the export and diff it against the committed file, byte for byte.

    Comparing package-by-package (as an earlier version of this test did) only
    catches a version that changed for a package already listed in
    requirements-lock.txt -- it misses a package added to uv.lock and never
    exported at all, which would resolve unconstrained by `pip install
    --constraint` and drift just the same. Regenerating and diffing the whole
    file catches additions and removals too, not just version bumps.
    """
    fresh = subprocess.run(
        [
            "uv",
            "export",
            "--no-hashes",
            "--no-dev",
            "--no-emit-project",
            "--format",
            "requirements-txt",
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout

    committed = (ROOT / "requirements-lock.txt").read_text()

    # Both files open with a 2-line "autogenerated by uv via ..." comment that
    # differs only in whether `-o requirements-lock.txt` appears -- cosmetic,
    # not a drift signal, so the comparison skips it.
    assert fresh.splitlines()[2:] == committed.splitlines()[2:], (
        "requirements-lock.txt is out of sync with uv.lock -- run `make lock-action`"
    )


def test_requirements_lock_excludes_the_project_itself():
    """`-e .` (an editable self-install) is invalid inside a pip constraints file.

    `tri-review` legitimately appears in `# via tri-review` annotation comments
    (it's a dependent, not a pin), so this checks actual requirement lines --
    parsed pins and any `-e`/editable line -- rather than the raw text.
    """
    lines = (ROOT / "requirements-lock.txt").read_text().splitlines()
    assert not any(line.strip().startswith(("-e ", "-e\t")) for line in lines)
    assert "tri-review" not in _requirements_lock_versions()
